Fix inits
Shebang and missing variable sigils

diff --git a/etc/init.d/fail2ban b/etc/init.d/fail2ban
--- a/etc/init.d/fail2ban
+++ b/etc/init.d/fail2ban
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/usr/bin/env sh
 ### BEGIN INIT INFO
 # Provides:          fail2ban
 # Required-Start:    $local_fs $remote_fs
@@ -28,19 +28,19 @@ DAEMON=/usr/bin/$NAME-client
 SCRIPTNAME=/etc/init.d/$NAME
 CONFPATH="/usr/mailcleaner/etc/fail2ban/"
 
-SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
+SRCDIR=$(grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
 if [ "SRCDIR" = "" ]; then
-  SRCDIR=/opt/mailcleaner
+	SRCDIR=/opt/mailcleaner
 fi
 
-VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
+VARDIR=$(grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
 if [ "VARDIR" = "" ]; then
-  VARDIR=/var/mailcleaner
+	VARDIR=/var/mailcleaner
 fi
 
 # Ad-hoc way to parse out socket file name
-SOCKFILE=`grep -h '^[^#]*socket *=' /etc/$NAME/$NAME.conf /etc/$NAME/$NAME.local 2>/dev/null \
-          | tail -n 1 | sed -e 's/.*socket *= *//g' -e 's/ *$//g'`
+SOCKFILE=$(grep -h '^[^#]*socket *=' /etc/$NAME/$NAME.conf /etc/$NAME/$NAME.local 2>/dev/null |
+	tail -n 1 | sed -e 's/.*socket *= *//g' -e 's/ *$//g')
 [ -z "$SOCKFILE" ] && SOCKFILE='/tmp/fail2ban.sock'
 
 # Exit if the package is not installed
@@ -58,7 +58,7 @@ DAEMON_ARGS="$FAIL2BAN_OPTS"
 
 # Predefine what can be missing from lsb source later on -- necessary to run
 # on sarge. Just present it in a bit more compact way from what was shipped
-log_daemon_msg () {
+log_daemon_msg() {
 	[ -z "$1" ] && return 1
 	echo -n "$1:"
 	[ -z "$2" ] || echo -n " $2"
@@ -73,8 +73,7 @@ log_daemon_msg () {
 #
 # Shortcut function for abnormal init script interruption
 #
-report_bug()
-{
+report_bug() {
 	echo $*
 	echo "Please submit a bug report to Debian BTS (reportbug fail2ban)"
 	exit 1
@@ -84,8 +83,7 @@ report_bug()
 # Helper function to check if socket is present, which is often left after
 # abnormal exit of fail2ban and needs to be removed
 #
-check_socket()
-{
+check_socket() {
 	# Return
 	#	0 if socket is present and readable
 	#	1 if socket file is not present
@@ -100,8 +98,7 @@ check_socket()
 #
 # Function that starts the daemon/service
 #
-do_start()
-{
+do_start() {
 	# Return
 	#	0 if daemon has been started
 	#	1 if daemon was already running
@@ -109,7 +106,7 @@ do_start()
 	export PYENV_ROOT="/var/mailcleaner/.pyenv"
 	export PATH="$PYENV_ROOT/bin:$PATH"
 	if command -v pyenv 1>/dev/null 2>&1; then
-	  eval "$(pyenv init --path)"
+		eval "$(pyenv init --path)"
 	fi
 	dump_fail2ban_config.py
 
@@ -118,9 +115,9 @@ do_start()
 
 	if [ -e "$SOCKFILE" ]; then
 		log_failure_msg "Socket file $SOCKFILE is present"
-		[ "$1" = "force-start" ] \
-			&& log_success_msg "Starting anyway as requested" \
-			|| return 2
+		[ "$1" = "force-start" ] &&
+			log_success_msg "Starting anyway as requested" ||
+			return 2
 		DAEMON_ARGS="$DAEMON_ARGS"
 	fi
 
@@ -138,48 +135,44 @@ do_start()
 	fi
 	DAEMON_ARGS="$DAEMON_ARGS -c $CONFPATH"
 	start-stop-daemon --start --quiet --chuid "$FAIL2BAN_USER" --exec $DAEMON -- \
-		$DAEMON_ARGS start > /dev/null\
-		|| return 2
-    	rm $VARDIR/run/fail2ban.stopped >/dev/null 2>&1
-    	rm $VARDIR/run/fail2ban.*.rs >/dev/null 2>&1
+		$DAEMON_ARGS start >/dev/null || return 2
+	rm $VARDIR/run/fail2ban.stopped >/dev/null 2>&1
+	rm $VARDIR/run/fail2ban.*.rs >/dev/null 2>&1
 	return 0
 }
-
 
 #
 # Function that checks the status of fail2ban and returns
 # corresponding code
 #
-do_status()
-{
-	$DAEMON ping > /dev/null 2>&1
+do_status() {
+	$DAEMON ping >/dev/null 2>&1
 	return $?
 }
 
 #
 # Function that stops the daemon/service
 #
-do_stop()
-{
+do_stop() {
 	# Return
 	#	0 if daemon has been stopped
 	#	1 if daemon was already stopped
 	#	2 if daemon could not be stopped
 	#	other if a failure occurred
 	touch $VARDIR/run/fail2ban.stop.rs
-	$DAEMON status > /dev/null 2>&1 || return 1
-	$DAEMON stop > /dev/null || return 2
+	$DAEMON status >/dev/null 2>&1 || return 1
+	$DAEMON stop >/dev/null || return 2
 	# now we need actually to wait a bit since it might take time
 	# for server to react on client's stop request. Especially
 	# important for restart command on slow boxes
 	count=1
 	while do_status && [ $count -lt 60 ]; do
 		sleep 1
-		count=$(($count+1))
+		count=$(($count + 1))
 	done
 	[ $count -lt 60 ] || return 3 # failed to stop
-    	rm $VARDIR/run/fail2ban.stop.rs >/dev/null 2>&1
-    	touch $VARDIR/run/fail2ban.stopped
+	rm $VARDIR/run/fail2ban.stop.rs >/dev/null 2>&1
+	touch $VARDIR/run/fail2ban.stopped
 	return 0
 }
 
@@ -187,7 +180,7 @@ do_stop()
 # Function to reload configuration
 #
 do_reload() {
-	$DAEMON reload > /dev/null && return 0 || return 1
+	$DAEMON reload >/dev/null && return 0 || return 1
 	return 0
 }
 
@@ -195,8 +188,7 @@ do_reload() {
 # shortcut function to don't duplicate case statements and to don't use
 # bashisms (arrays). Fixes #368218
 #
-log_end_msg_wrapper()
-{
+log_end_msg_wrapper() {
 	if [ "$3" != "no" ]; then
 		[ $1 -lt $2 ] && value=0 || value=1
 		log_end_msg $value
@@ -205,62 +197,62 @@ log_end_msg_wrapper()
 
 command="$1"
 case "$command" in
-	start|force-start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-		do_start "$command"
-		log_end_msg_wrapper $? 2 "$VERBOSE"
-		;;
+start | force-start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start "$command"
+	log_end_msg_wrapper $? 2 "$VERBOSE"
+	;;
 
-	stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		log_end_msg_wrapper $? 2 "$VERBOSE"
-		;;
+stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	log_end_msg_wrapper $? 2 "$VERBOSE"
+	;;
 
-	restart|force-reload)
-		touch $VARDIR/run/fail2ban.restart.rs
-		log_daemon_msg "Restarting $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0|1)
-				do_start
-				log_end_msg_wrapper $? 1 "always"
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
- 		esac
-		;;
-
-	reload|force-reload)
-        log_daemon_msg "Reloading $DESC" "$NAME"
-        do_reload
-        log_end_msg $?
-        ;;
-
-	status)
-		log_daemon_msg "Status of $DESC"
-		do_status
-		case $? in
-			0)  log_success_msg " $NAME is running" ;;
-			255)
-				check_socket
-				case $? in
-					1)  log_failure_msg " $NAME is not running" && exit 3 ;;
-					0)  log_failure_msg " $NAME is not running but $SOCKFILE exists" && exit 3 ;;
-					2)  log_failure_msg " $SOCKFILE not readable, status of $NAME is unknown" && exit 3 ;;
-					3)  log_failure_msg " $SOCKFILE exists but not a socket, status of $NAME is unknown" && exit 3 ;;
-					*)  report_bug "Unknown return code from $NAME:check_socket." && exit 4 ;;
-				esac
-				;;
-			*)  report_bug "Unknown $NAME status code" && exit 4
-		esac
+restart | force-reload)
+	touch $VARDIR/run/fail2ban.restart.rs
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	0 | 1)
+		do_start
+		log_end_msg_wrapper $? 1 "always"
 		;;
 	*)
-		echo "Usage: $SCRIPTNAME {start|force-start|stop|restart|force-reload|status}" >&2
-		exit 3
+		# Failed to stop
+		log_end_msg 1
 		;;
+	esac
+	;;
+
+reload | force-reload)
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
+	;;
+
+status)
+	log_daemon_msg "Status of $DESC"
+	do_status
+	case $? in
+	0) log_success_msg " $NAME is running" ;;
+	255)
+		check_socket
+		case $? in
+		1) log_failure_msg " $NAME is not running" && exit 3 ;;
+		0) log_failure_msg " $NAME is not running but $SOCKFILE exists" && exit 3 ;;
+		2) log_failure_msg " $SOCKFILE not readable, status of $NAME is unknown" && exit 3 ;;
+		3) log_failure_msg " $SOCKFILE exists but not a socket, status of $NAME is unknown" && exit 3 ;;
+		*) report_bug "Unknown return code from $NAME:check_socket." && exit 4 ;;
+		esac
+		;;
+	*) report_bug "Unknown $NAME status code" && exit 4 ;;
+	esac
+	;;
+*)
+	echo "Usage: $SCRIPTNAME {start|force-start|stop|restart|force-reload|status}" >&2
+	exit 3
+	;;
 esac
 
 :
diff --git a/etc/init.d/messagesniffer b/etc/init.d/messagesniffer
--- a/etc/init.d/messagesniffer
+++ b/etc/init.d/messagesniffer
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/usr/bin/env sh
 ### BEGIN INIT INFO
 # Provides:          SNFServer
 # Required-Start:    $syslog $remote_fs $network $named
@@ -23,37 +23,37 @@
 ####
 ## Olivier Diserens, for MailCleaner
 ###
-SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
-if [ "SRCDIR" = "" ]; then
-  SRCDIR=/opt/mailcleaner
+SRCDIR=$(grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
+if [ "$SRCDIR" = "" ]; then
+	SRCDIR=/opt/mailcleaner
 fi
-VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
-if [ "VARDIR" = "" ]; then
-  VARDIR=/var/mailcleaner
-fi
-
-if [ ! -d $VARDIR/spool/messagesniffer ];then 
-  mkdir $VARDIR/spool/messagesniffer
-  chown snfuser:snfuser $VARDIR/spool/messagesniffer
+VARDIR=$(grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
+if [ "$VARDIR" = "" ]; then
+	VARDIR=/var/mailcleaner
 fi
 
-if [ ! -d $VARDIR/log/messagesniffer ];then 
-  mkdir $VARDIR/log/messagesniffer
-  chown snfuser:snfuser $VARDIR/log/messagesniffer
+if [ ! -d $VARDIR/spool/messagesniffer ]; then
+	mkdir $VARDIR/spool/messagesniffer
+	chown snfuser:snfuser $VARDIR/spool/messagesniffer
 fi
 
-if [ ! -d $VARDIR/run/messagesniffer ];then
-  mkdir $VARDIR/run/messagesniffer
-  chown snfuser:snfuser $VARDIR/run/messagesniffer
+if [ ! -d $VARDIR/log/messagesniffer ]; then
+	mkdir $VARDIR/log/messagesniffer
+	chown snfuser:snfuser $VARDIR/log/messagesniffer
 fi
 
-prepare () {
-  $SRCDIR/bin/dump_messagesniffer_config.pl >/dev/null 2>&1
+if [ ! -d $VARDIR/run/messagesniffer ]; then
+	mkdir $VARDIR/run/messagesniffer
+	chown snfuser:snfuser $VARDIR/run/messagesniffer
+fi
 
-  if [ ! -f $VARDIR/spool/messagesniffer/GBUdbIgnoreList.txt ]; then
-    cp /opt/messagesniffer/share/snf-server/GBUdbIgnoreList.txt.sample $VARDIR/spool/messagesniffer/GBUdbIgnoreList.txt
-  fi
-  cp /opt/messagesniffer/share/snf-server/*.snf $VARDIR/spool/messagesniffer/
+prepare() {
+	$SRCDIR/bin/dump_messagesniffer_config.pl >/dev/null 2>&1
+
+	if [ ! -f $VARDIR/spool/messagesniffer/GBUdbIgnoreList.txt ]; then
+		cp /opt/messagesniffer/share/snf-server/GBUdbIgnoreList.txt.sample $VARDIR/spool/messagesniffer/GBUdbIgnoreList.txt
+	fi
+	cp /opt/messagesniffer/share/snf-server/*.snf $VARDIR/spool/messagesniffer/
 }
 ## End Mailcleaner
 
@@ -65,9 +65,8 @@ debugModeFile=$runDir/debug_mode
 productionModeFile=$runDir/production_mode
 
 # Set debug mode flag.
-if [ -f $debugModeFile ]
-then
-    debugMode=true
+if [ -f $debugModeFile ]; then
+	debugMode=true
 fi
 
 # Debug output file.
@@ -132,84 +131,81 @@ SCRIPTNAME=/etc/init.d/$NAME
 #
 # Function to create the mode file.
 #
-createModeFile()
-{
-    fileName=$1
+createModeFile() {
+	fileName=$1
 
-    # Remove any existing mode files.
-    rm -f $productionModeFile $debugModeFile $fileName
-    (
-	echo "snf-server mode file"
-	echo
-	echo "This file specifies whether snf-server is configured to run in"
-	echo "production mode or debug mode.  If the name of this file is"
-        echo "'production_mode', then snf-server is configured to run in"
-        echo "production mode.  If the name is 'debug_mode', then snf-server is"
-        echo "configured to run in debug mode."
-	echo
-	echo "To run in debug mode:"
-	echo
-	echo "    1) Run 'snf-server debug_mode'"
-	echo
-	echo "    2) Run 'snf-server restart' (if snf-server is already running),"
-	echo "       or 'snf-server start' (to start snf-server)"
-	echo
-	echo "To run in production mode:"
-	echo
-	echo "    1) Run 'snf-server production_mode'"
-	echo
-	echo "    2) Run 'snf-server restart' (if snf-server is already running),"
-	echo "       or 'snf-server start' (to start snf-server)"
-	echo
-	echo "By default, snf-server is configured to run in production mode."
-	) > $fileName
+	# Remove any existing mode files.
+	rm -f $productionModeFile $debugModeFile $fileName
+	(
+		echo "snf-server mode file"
+		echo
+		echo "This file specifies whether snf-server is configured to run in"
+		echo "production mode or debug mode.  If the name of this file is"
+		echo "'production_mode', then snf-server is configured to run in"
+		echo "production mode.  If the name is 'debug_mode', then snf-server is"
+		echo "configured to run in debug mode."
+		echo
+		echo "To run in debug mode:"
+		echo
+		echo "    1) Run 'snf-server debug_mode'"
+		echo
+		echo "    2) Run 'snf-server restart' (if snf-server is already running),"
+		echo "       or 'snf-server start' (to start snf-server)"
+		echo
+		echo "To run in production mode:"
+		echo
+		echo "    1) Run 'snf-server production_mode'"
+		echo
+		echo "    2) Run 'snf-server restart' (if snf-server is already running),"
+		echo "       or 'snf-server start' (to start snf-server)"
+		echo
+		echo "By default, snf-server is configured to run in production mode."
+	) >$fileName
 
 }
 
 #
 # Function that starts the daemon/service
 #
-do_start()
-{
+do_start() {
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
 
 	start-stop-daemon --chuid $userName --start --quiet \
-	    --exec $PRODUCTION_DAEMON --test > /dev/null 2>&1 \
-	    || return 1
+		--exec $PRODUCTION_DAEMON --test >/dev/null 2>&1 ||
+		return 1
 
-	if [ $debugMode ]
-	then
+	if [ $debugMode ]; then
 
-	    # Enable core dumps.
-	    ulimit -c unlimited
+		# Enable core dumps.
+		ulimit -c unlimited
 
-	    # Add date to the debug file.
-	    echo "Starting $DEBUG_DAEMON $DEBUG_DAEMON_ARGS on " $(date) >> \
-		$debugOutputFile
-            chown $userName:$groupName $debugOutputFile
+		# Add date to the debug file.
+		echo "Starting $DEBUG_DAEMON $DEBUG_DAEMON_ARGS on " $(date) >> \
+			$debugOutputFile
+		chown $userName:$groupName $debugOutputFile
 
-	    # Start with output redirected.
-	    start-stop-daemon --chuid $userName --start --quiet \
-		--chdir $runDir \
-		--exec $DEBUG_DAEMON -- $DEBUG_DAEMON_ARGS >> \
-		$debugOutputFile 2>&1 \
-		|| return 2 &
+		# Start with output redirected.
+		start-stop-daemon --chuid $userName --start --quiet \
+			--chdir $runDir \
+			--exec $DEBUG_DAEMON -- $DEBUG_DAEMON_ARGS >> \
+			$debugOutputFile 2>&1 ||
+			return 2 &
 	else
-echo $PRODUCTION_DAEMON $PRODUCTION_DAEMON_ARGS
-	    start-stop-daemon --chuid $userName --start --quiet \
-		--chdir $runDir \
-		--background --exec $PRODUCTION_DAEMON -- \
-		$PRODUCTION_DAEMON_ARGS > /dev/null 2>&1 || return 2
+		echo $PRODUCTION_DAEMON $PRODUCTION_DAEMON_ARGS
+		start-stop-daemon --chuid $userName --start --quiet \
+			--chdir $runDir \
+			--background --exec $PRODUCTION_DAEMON -- \
+			$PRODUCTION_DAEMON_ARGS >/dev/null 2>&1 || return 2
 	fi
 
 	# Check that process started.
-	$dir/$clientProg -status.second > /dev/null 2>&1
+	$dir/$clientProg -status.second >/dev/null 2>&1
 	RETVAL=$?
 	if [ $RETVAL -ne 0 ]; then
-	    RETVAL=2
+		RETVAL=2
 	fi
 	return $RETVAL
 }
@@ -217,37 +213,36 @@ echo $PRODUCTION_DAEMON $PRODUCTION_DAEMON_ARGS
 #
 # Function that stops the daemon/service
 #
-do_stop()
-{
+do_stop() {
 	# Return
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-        # Check whether SNFServer is running.
+	# Check whether SNFServer is running.
 	start-stop-daemon --chuid $userName --start --quiet \
-	    --exec $PRODUCTION_DAEMON --test > /dev/null
+		--exec $PRODUCTION_DAEMON --test >/dev/null
 	RETVAL=$?
 
 	if [ $RETVAL -ne 1 ]; then
-	    return 1
+		return 1
 	fi
 
 	# Issue shutdown command
-	$dir/$clientProg -shutdown > /dev/null 2>&1
+	$dir/$clientProg -shutdown >/dev/null 2>&1
 	sleep 10
 
-        # Check again whether SNFServer is running.
+	# Check again whether SNFServer is running.
 	start-stop-daemon --chuid $userName --start --quiet \
-	    --exec $PRODUCTION_DAEMON --test > /dev/null
+		--exec $PRODUCTION_DAEMON --test >/dev/null
 	RETVAL=$?
 
-	if [ $RETVAL -eq 1 ] ; then
-	    # Send TERM signal to stop SNFServer.
-	    start-stop-daemon --stop --quiet --retry=TERM/5 --exec $PRODUCTION_DAEMON
-	    RETVAL="$?"
-	    [ "$RETVAL" = 2 ] && return 2
-	    return "$RETVAL"
+	if [ $RETVAL -eq 1 ]; then
+		# Send TERM signal to stop SNFServer.
+		start-stop-daemon --stop --quiet --retry=TERM/5 --exec $PRODUCTION_DAEMON
+		RETVAL="$?"
+		[ "$RETVAL" = 2 ] && return 2
+		return "$RETVAL"
 	fi
 
 	# SNFServer isn't running.
@@ -256,36 +251,36 @@ do_stop()
 }
 
 case "$1" in
-  start)
+start)
 	[ "$VERBOSE" != no ] && log_daemon_msg "  Starting $DESC" "$NAME"
-        prepare
+	prepare
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  stop)
+stop)
 	[ "$VERBOSE" != no ] && log_daemon_msg "  Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  status)
+status)
 	start-stop-daemon --chuid $userName --start --quiet \
-	    --exec $PRODUCTION_DAEMON --test > /dev/null
+		--exec $PRODUCTION_DAEMON --test >/dev/null
 	RETVAL=$?
 	if [ $RETVAL -eq 0 ]; then
-	    # Stopped
-	    echo "$productionProg is stopped"
+		# Stopped
+		echo "$productionProg is stopped"
 	else
-	    # Running
-	    echo "$productionProg (pid $(pidof $PRODUCTION_DAEMON)) is running"
+		# Running
+		echo "$productionProg (pid $(pidof $PRODUCTION_DAEMON)) is running"
 	fi
 	;;
-  restart|force-reload)
+restart | force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
@@ -293,36 +288,36 @@ case "$1" in
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
-	  0|1)
+	0 | 1)
 		prepare
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+		0) log_end_msg 0 ;;
+		1) log_end_msg 1 ;; # Old process is still running
+		*) log_end_msg 1 ;; # Failed to start
 		esac
 		;;
-	  *)
-	  	# Failed to stop
+	*)
+		# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
-  debug_mode)
+debug_mode)
 	#
 	# Remove any mode flags, and create the debug_mode file.
 	#
 	log_daemon_msg "Switching to debug mode $DESC" "$NAME"
 	createModeFile $debugModeFile
 	;;
-  production_mode)
+production_mode)
 	#
 	# Remove any mode flags, and create the production_mode file.
 	#
 	log_daemon_msg "Switching to production mode $DESC" "$NAME"
 	createModeFile $productionModeFile
 	;;
-  *)
+*)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|production_mode|debug_mode}" >&2
 	exit 3
 	;;
diff --git a/etc/init.d/mysql_master b/etc/init.d/mysql_master
--- a/etc/init.d/mysql_master
+++ b/etc/init.d/mysql_master
@@ -1,23 +1,23 @@
-#!/bin/sh
+#!/usr/bin/env sh
 # MySQL (MariaDB) daemon start/stop script.
 
-SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
-if [ "SRCDIR" = "" ]; then
-  SRCDIR=/opt/mailcleaner
+SRCDIR=$(grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
+if [ "$SRCDIR" = "" ]; then
+	SRCDIR=/opt/mailcleaner
 fi
-VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
-if [ "VARDIR" = "" ]; then
-  VARDIR=/var/mailcleaner
+VARDIR=$(grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3)
+if [ "$VARDIR" = "" ]; then
+	VARDIR=/var/mailcleaner
 fi
 
 # Set some defaults
 pid_file=
-mode=$1    # start or stop
+mode=$1 # start or stop
 skip=$2
 
 SKIPGRANT=
 if [ "$skip" = "nopass" ]; then
-  SKIPGRANT="--skip-grant-table"
+	SKIPGRANT="--skip-grant-table"
 fi
 
 conf=$SRCDIR/etc/mysql/my_master.cnf
@@ -27,78 +27,75 @@ log_file=$VARDIR/log/mysql_master/mysql.log
 binlog=$VARDIR/log/mysql_master/mysql_bin.log
 socket=$VARDIR/run/mysql_master/mysqld.sock
 
-prepare () {
-  if [ ! -d $VARDIR/log/mysql_master ]; then mkdir $VARDIR/log/mysql_slave; fi
-  chown mysql:mailcleaner -R $VARDIR/log/mysql_master >/dev/null 2>&1
-  if [ ! -d $VARDIR/spool/mysql_master ]; then mkdir $VARDIR/log/mysql_slave; fi
-  chown mysql:mailcleaner -R $VARDIR/spool/mysql_master >/dev/null 2>&1
-  $SRCDIR/bin/dump_mysql_config.pl >/dev/null 2>&1
+prepare() {
+	if [ ! -d $VARDIR/log/mysql_master ]; then mkdir $VARDIR/log/mysql_slave; fi
+	chown mysql:mailcleaner -R $VARDIR/log/mysql_master >/dev/null 2>&1
+	if [ ! -d $VARDIR/spool/mysql_master ]; then mkdir $VARDIR/log/mysql_slave; fi
+	chown mysql:mailcleaner -R $VARDIR/spool/mysql_master >/dev/null 2>&1
+	$SRCDIR/bin/dump_mysql_config.pl >/dev/null 2>&1
 }
 
 case "$mode" in
-  'start')
-    touch $VARDIR/run/mysql_master.start.rs
-    # Start daemon
-    echo -n "  Starting master DB: "
-    prepare
-    if test -x /usr/bin/mariadbd-safe
-    then
-	/usr/bin/mariadbd-safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log-bin=$binlog --log-error=$log_file --socket=$socket $SKIPGRANT >/dev/null 2>&1 &
-    else
-      echo "Can't execute /usr/bin/mariadbd-safe"
-    fi
-    if [ -f $VARDIR/run/mysql_master.rn ]; then
-      rm $VARDIR/run/mysql_master.rn
-    fi
-    echo "started."
-    rm $VARDIR/run/mysql_master.stopped >/dev/null 2>&1
-    rm $VARDIR/run/mysql_master.*.rs >/dev/null 2>&1
-    ;;
+'start')
+	touch $VARDIR/run/mysql_master.start.rs
+	# Start daemon
+	echo -n "  Starting master DB: "
+	prepare
+	if test -x /usr/bin/mariadbd-safe; then
+		/usr/bin/mariadbd-safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log-bin=$binlog --log-error=$log_file --socket=$socket $SKIPGRANT >/dev/null 2>&1 &
+	else
+		echo "Can't execute /usr/bin/mariadbd-safe"
+	fi
+	if [ -f $VARDIR/run/mysql_master.rn ]; then
+		rm $VARDIR/run/mysql_master.rn
+	fi
+	echo "started."
+	rm $VARDIR/run/mysql_master.stopped >/dev/null 2>&1
+	rm $VARDIR/run/mysql_master.*.rs >/dev/null 2>&1
+	;;
 
-  'stop')
-    touch $VARDIR/run/mysql_master.stop.rs
-    # Stop daemon. We use a signal here to avoid having to know the
-    # root password.
-    echo -n "  Stopping master DB: "
-    if test -s "$pid_file"
-    then
-      mysqld_pid=`cat $pid_file`
-      kill $mysqld_pid
+'stop')
+	touch $VARDIR/run/mysql_master.stop.rs
+	# Stop daemon. We use a signal here to avoid having to know the
+	# root password.
+	echo -n "  Stopping master DB: "
+	if test -s "$pid_file"; then
+		mysqld_pid=$(cat $pid_file)
+		kill $mysqld_pid
 
-      # mysqld should remove the pid_file when it exits, so wait for it.
-      sleep 1
-      while [ -s $pid_file -a "$flags" != aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ]
-      do
-	[ -z "$flags" ] && echo $echo_n "Wait for mariadbd to exit$echo_c" || echo $echo_n ".$echo_c"
-        flags=a$flags
-        sleep 1
-      done
-      if [ -s $pid_file ]
-         then echo -n " gave up waiting! "
-      elif [ -n "$flags" ]
-         then echo " stopped."
-      fi
-    else
-      echo -n "No mariadbd pid file found. Looked for $pid_file. "
-    fi
-    kill -KILL $(pgrep -f my_master.cnf) >/dev/null 2>&1
-    sleep 2
-    echo "stopped."
-    rm $VARDIR/run/mysql_master.stop.rs >/dev/null 2>&1
-    touch $VARDIR/run/mysql_master.stopped
-    ;;
+		# mysqld should remove the pid_file when it exits, so wait for it.
+		sleep 1
+		while [ -s $pid_file -a "$flags" != aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ]; do
+			[ -z "$flags" ] && echo $echo_n "Wait for mariadbd to exit$echo_c" || echo $echo_n ".$echo_c"
+			flags=a$flags
+			sleep 1
+		done
+		if [ -s $pid_file ]; then
+			echo -n " gave up waiting! "
+		elif [ -n "$flags" ]; then
+			echo " stopped."
+		fi
+	else
+		echo -n "No mariadbd pid file found. Looked for $pid_file. "
+	fi
+	kill -KILL $(pgrep -f my_master.cnf) >/dev/null 2>&1
+	sleep 2
+	echo "stopped."
+	rm $VARDIR/run/mysql_master.stop.rs >/dev/null 2>&1
+	touch $VARDIR/run/mysql_master.stopped
+	;;
 
-  'restart')
-    touch $VARDIR/run/mysql_master.restart.rs
-    # Stop the service and regardless of whether it was
-    # running or not, start it again.
-    $0 stop
-    $0 start $skip
-		;;
+'restart')
+	touch $VARDIR/run/mysql_master.restart.rs
+	# Stop the service and regardless of whether it was
+	# running or not, start it again.
+	$0 stop
+	$0 start $skip
+	;;
 
-  *)
-    # usage
-    echo "Usage: $0 start|stop|restart"
-    exit 1
-    ;;
+*)
+	# usage
+	echo "Usage: $0 start|stop|restart"
+	exit 1
+	;;
 esac
