Resolve mariadb issues
Both init scripts work.
DB check/repair work.
mc_mysql connects and database seem to be intact

TODO:
resync (mostly) works. However 'Slave_IO_State' is ''. Need to
investigate.

diff --git a/etc/init.d/mysql_slave b/etc/init.d/mysql_slave
--- a/etc/init.d/mysql_slave
+++ b/etc/init.d/mysql_slave
@@ -1,5 +1,5 @@
 #!/bin/sh
-# MySQL daemon start/stop script.
+# MySQL (MariaDB) daemon start/stop script.
 
 SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
 if [ "SRCDIR" = "" ]; then
@@ -10,24 +10,8 @@ if [ "VARDIR" = "" ]; then
   VARDIR=/var/mailcleaner
 fi
 
-basedir=
-
-# The following variables are only set for letting mysql.server find things.
-
 # Set some defaults
-datadir=/var/mysql5
 pid_file=
-if test -z "$basedir"
-then
-  basedir=/opt/mysql5
-  bindir=/opt/mysql5/bin
-else
-  bindir="$basedir/bin"
-fi
-
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:$basedir/bin
-export PATH
-
 mode=$1    # start or stop
 skip=$2
 
@@ -44,24 +28,23 @@ binlog=$VARDIR/log/mysql_slave/mysql_bin.log
 socket=$VARDIR/run/mysql_slave/mysqld.sock
 
 prepare () {
-  chown mysql:mailcleaner $VARDIR/log/mysql_slave/mysql.log >/dev/null 2>&1
-
+  if [ ! -d $VARDIR/log/mysql_slave ]; then mkdir $VARDIR/log/mysql_slave; fi
+  chown mysql:mailcleaner -R $VARDIR/log/mysql_slave >/dev/null 2>&1
+  if [ ! -d $VARDIR/spool/mysql_slave ]; then mkdir $VARDIR/spool/mysql_slave; fi
+  chown mysql:mailcleaner -R $VARDIR/spool/mysql_slave >/dev/null 2>&1
   $SRCDIR/bin/dump_mysql_config.pl >/dev/null 2>&1
 }
 
 case "$mode" in
   'start')
     touch $VARDIR/run/mysql_slave.start.rs
-    # Start daemon
-
     echo -n "  Starting slave DB: "
     prepare
-    if test -x $bindir/mysqld_safe
+    if test -x /usr/bin/mariadbd-safe
     then
-#$bindir/mysqld_safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log=$log_file --socket=$socket >/dev/null 2>&1 &
-	$bindir/mysqld_safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log-error=$log_file --socket=$socket $SKIPGRANT >/dev/null 2>&1 &
+	/usr/bin/mariadbd-safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log-bin=$binlog --log-error=$log_file --socket=$socket $SKIPGRANT >/dev/null 2>&1 &
     else
-      echo "Can't execute $bindir/mysqld_safe from dir $basedir"
+      echo "Can't execute /usr/bin/mariadbd-safe"
     fi
     if [ -f $VARDIR/run/mysql_slave.rn ]; then
       rm $VARDIR/run/mysql_slave.rn
@@ -80,14 +63,13 @@ case "$mode" in
     if test -s "$pid_file"
     then
       mysqld_pid=`cat $pid_file`
-      #echo "Killing mysqld with pid $mysqld_pid"
       kill $mysqld_pid
-      # mysqld should remove the pid_file when it exits, so wait for it.
 
+      # mysqld should remove the pid_file when it exits, so wait for it.
       sleep 1
       while [ -s $pid_file -a "$flags" != aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ]
       do
-	[ -z "$flags" ] && echo $echo_n "Wait for mysqld to exit$echo_c" || echo $echo_n ".$echo_c"
+	[ -z "$flags" ] && echo $echo_n "Wait for mariadbd to exit$echo_c" || echo $echo_n ".$echo_c"
         flags=a$flags
         sleep 1
       done
@@ -97,7 +79,7 @@ case "$mode" in
          then echo " stopped."
       fi
     else
-      echo -n "No mysqld pid file found. Looked for $pid_file. "
+      echo -n "No mariadbd pid file found. Looked for $pid_file. "
     fi
     echo "stopped."
     rm $VARDIR/run/mysql_slave.stop.rs >/dev/null 2>&1
